// Renders the full docs/API.md reference from the merged endpoint model.
export function renderApiDoc(endpoints) {
  const lines = [
    "# API Reference",
    "",
    "> Auto-generated by `npm run docs:sync` from `backend/src/routes`, `controllers`, and `validators`.",
    "> Do not edit this file by hand — update the source code comments/schemas and re-run the sync instead.",
    "",
  ];

  for (const ep of endpoints) {
    lines.push(`## ${ep.method} ${ep.path}`, "", ep.description, "");

    if (ep.requestSchema && ep.requestSchema.fields.length) {
      lines.push(
        "**Request Body**",
        "",
        "| Field | Type | Required | Constraints |",
        "|-------|------|----------|-------------|"
      );
      for (const f of ep.requestSchema.fields) {
        lines.push(`| \`${f.name}\` | ${f.type} | ${f.required ? "yes" : "no"} | ${f.constraints.join("; ") || "—"} |`);
      }
      lines.push("");
    }

    if (ep.responses.length) {
      lines.push("**Responses**", "");
      for (const r of ep.responses) lines.push(`- \`${r.status}\` — ${r.meaning}`);
      lines.push("");
    }

    lines.push("---", "");
  }

  return lines.join("\n").replace(/\n+$/, "\n");
}
